Traceback (most recent call last):
  File "/Users/manas/Documents/_projects/DBLite/dblite.py", line 475, in <module>
    main()
  File "/Users/manas/Documents/_projects/DBLite/dblite.py", line 468, in main
    server = DBLiteServer(host=options.host, port=options.port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manas/Documents/_projects/DBLite/dblite.py", line 145, in __init__
    self.server = ThreadedTCPServer((host, port), self._threaded_handler_class())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/opt/anaconda3/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
